### ISSUE TITLE
Raspberry pi zero 2

### ISSUE THREAD

**Issue by actraiser30** [HinTak/RaspberryPi-Dev#5]
Hello again sorry for the inconvenience if any

is it possible to update your berryboot version for the PI4 or the PI0123 to work with the newest raspberry pi zero 2 ??

any of the older versions i tried did not work

thanks

**Comment by HinTak** [comment]
On the whole, I think it is best you report upstream - and it has indeed been reported upstream : https://github.com/maxnet/berryboot/issues/729 , and also mentioned in https://github.com/maxnet/berryboot/issues/723 . 

I think the appropriate action is to report upstream and @ me, rather than put it here...

**Comment by symbios24** [comment]
Dont worry i wont bother you again
Bye

**Comment by HinTak** [comment]
Are you using two different github account? Either way, I think it is best discuss this issue upstream.
